// flow-typed signature: 3a9fe892aae7feaf523004752ea89b3b
// flow-typed version: <<STUB>>/clark-styles_v^0.7.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clark-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clark-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clark-styles/dist/index.es' {
  declare module.exports: any;
}

declare module 'clark-styles/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clark-styles/dist/index.es.js' {
  declare module.exports: $Exports<'clark-styles/dist/index.es'>;
}
declare module 'clark-styles/dist/index.js' {
  declare module.exports: $Exports<'clark-styles/dist/index'>;
}
